version: '2'

services:
  app:
    build: .
    volumes:
    - "./:/app"
    expose:
      - '3000'
    ports:
      - '3001:3000'
    links:
      - redis

  redis:
    image: redis
    restart: always
    expose:
      - '6379'
    ports:
      - '6379:6379'
